# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Fabric Properties
# Check versions at https://fabricmc.net/develop
# Versions are centralized in gradle/libs.versions.toml

# Mod Properties
mod_version=1.3.0
maven_group=mod.timberfall
archives_base_name=timberfall