# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# Check versions at https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.1

# Mod Properties
mod_version=1.1.0
maven_group=mod.timberfall
archives_base_name=timberfall

# Dependencies
fabric_version=0.160.5+26.3